global using Xunit;
global using FluentAssertions;
global using Moq;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using AutoFixture;
global using System.Text.Json;
global using System.Text;